### ISSUE TITLE
Plugin 

### ISSUE THREAD

**Issue by kisaapear** [Kingbobs/Relics#1]
awesome

**Comment by MakerbakerYT** [comment]
> `on[ojb[ono[iiiiiiiii[b[oio[in[oin[oinoin[oin[oin[onin[in[oin[oin
### ### **pnon[n;;kj  @j'ojb'ojknnnkn;lknn]pin]oin[onk; ;kj'n'kn'k ;m  j;kj kn
l, 'lj 'j j`**

**Comment by Kingbobs** [comment]
nothing
