### ISSUE TITLE
I can help

### ISSUE THREAD

**Issue by TetroYT** [Kingbobs/Relics#3]
Just tell me what needs testing and I can test it for you I usually reply within an hour so just tell me what ever and you’ll get an answer

**Comment by Kingbobs** [comment]
I need u to dowload the plugin and test it on the servet any server and tell me errors

**Comment by TetroYT** [comment]
No errors on start up you receive the relics but when you try to place them they glitch back to your inventory

**Comment by TetroYT** [comment]
do they have any dependant plugins i need to install?

**Comment by Kingbobs** [comment]
Try with inv plugin

**Comment by TetroYT** [comment]
Inv menu by muqsit?

**Comment by Kingbobs** [comment]
Yes any

**Comment by TetroYT** [comment]
I tried with inv menu and still the same issue

**Comment by Kingbobs** [comment]
Ok im see about the plugin and why it not opening thank u for do this
